version: "3"
services:
  kserver:
    image: isx46410800/k19:kserver
    container_name: kserver.edt.org
    hostname: kserver.edt.org
    ports:
      - "88:88"
      - "464:464"
      - "749:749"
    networks:
      - mynet
  ldap:
    image: isx46410800/k19:ldapserver
    container_name: ldap.edt.org
    hostname: ldap.edt.org
    ports: 
      - "389:389"
    networks:
      - mynet
  sshd:
    image: isx46410800/k19:sshdpl
    container_name: sshd.edt.org
    hostname: sshd.edt.org
    ports:
      - "1022:22"
    networks:
      - mynet
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - mynet
networks:
  mynet:
