# Version: 0.0.1
# @edt M11 2019-2020
# calendar
# -------------------------------------
FROM fedora:27
LABEL author="@edt ASIX M11-SAD"
LABEL description="Exemple utilització entrypoint 2019-2020"
ENTRYPOINT [ "/usr/bin/cal" ]
CMD ["2019"]
